openapi: 3.0.3
info:
  title: Devsu Test for Person microservice - OpenAPI 3.0
  description: |-
    This API contains:
    - CRUD operations for Person and Client
  contact:
    email: sergio.hidalgo.e@gmail.com
  version: 1.0.0
servers:
  - url: localhost:8080
tags:
  - name: client
    description: Access to client operations
paths:
  /clients:
    get:
      summary: List all clients
      operationId: getClients
      responses:
        '200':
          description: List of clients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Client'
    post:
      summary: Create a new client
      operationId: createClient
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
      responses:
        '201':
          description: Client created
  /clients/{id}:
    get:
      summary: Get a client by ID
      operationId: getClient
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A single client
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
        '404':
          description: Client not found
    patch:
      summary: Partially update a client by ID
      operationId: updateClient
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
      responses:
        '200':
          description: Client partially updated
        '404':
          description: Client not found
    delete:
      summary: Delete a client by ID
      operationId: deleteClient
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Client deleted
        '404':
          description: Client not found

components:
  schemas:
    Person:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        gender:
          type: string
          enum:
            - MALE
            - FEMALE
            - OTHER
        age:
          type: integer
        identification:
          type: string
        address:
          type: string
        phone:
          type: string

    Client:
      type: object
      allOf:
        - $ref: '#/components/schemas/Person'
        - type: object
          properties:
            id:
              type: integer
              format: int64
            clientId:
              type: string
            password:
              type: string
            status:
              type: string